import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Sidebar } from "lucide-react";
import SidebarComp from "./_components/Sidebar";
import { ScoreProvider } from "./_components/ScoreContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WhatBytes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <SidebarComp />
        <ScoreProvider>{children}</ScoreProvider>
      </body>
    </html>
  );
}
